### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by Kismetzc** [SysCV/qd-3dt#21] opened 2021-07-28 10:06 UTC
Following the file `GETTING_STARTED.md`, I reproduced your result on the Nuscens dataset. But I don't know how to visualize it?

**Comment by tobiasfshr** [comment] 2021-07-29 07:27
Duplicate of #19. Closing.

**Closed by tobiasfshr** 2021-07-29 07:27 UTC

**Comment by Kismetzc** [comment] 2021-07-29 09:34
According to your instructions, I modified the code `video. parser.add_argument('--show', action='store_true', help='show results')`  to `video. parser.add_argument('--show', action='store_true', help='show results',default='True')`. And I ran the code 
 ```
./scripts/run_test_nusc.sh work_dirs/Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter/output_test_box3d_deep_depth_motion_lstm_3dcen configs/Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter.py 0 1 --data_split_prefix val --full_frames
 ```
But there aren't any videos.

**Comment by GitRooky** [comment] 2022-02-21 15:10
@Kismetzc Have you solve the problem?
